name: adishakti
description: A comprehensive safety application designed to enhance women's security during travel and daily commutes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  flutter_webrtc: ^0.9.47
  flutter_local_notifications: ^16.3.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 